package br.com.models.vo;
// Generated 19/06/2015 12:08:25 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Funcionario generated by hbm2java
 */
@Entity
@Table(name="funcionario"
    ,catalog="dbloja"
)
public class Funcionario  implements java.io.Serializable {


     private Long idFuncionario;
     private Contato contato;
     private Endereco endereco;
     private Pessoa pessoa;
     private String nomeFuncionario;
     private String cargoFuncionario;
     private String usuarioFuncionario;
     private String senhaFuncionario;
     private Date criacaoFuncionario;
     private Date atualizacaoFuncionario;

    public Funcionario() {
    }

    public Funcionario(Contato contato, Endereco endereco, Pessoa pessoa, String nomeFuncionario, String cargoFuncionario, String usuarioFuncionario, String senhaFuncionario, Date criacaoFuncionario, Date atualizacaoFuncionario) {
       this.contato = contato;
       this.endereco = endereco;
       this.pessoa = pessoa;
       this.nomeFuncionario = nomeFuncionario;
       this.cargoFuncionario = cargoFuncionario;
       this.usuarioFuncionario = usuarioFuncionario;
       this.senhaFuncionario = senhaFuncionario;
       this.criacaoFuncionario = criacaoFuncionario;
       this.atualizacaoFuncionario = atualizacaoFuncionario;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idFuncionario", unique=true, nullable=false)
    public Long getIdFuncionario() {
        return this.idFuncionario;
    }
    
    public void setIdFuncionario(Long idFuncionario) {
        this.idFuncionario = idFuncionario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="contatoFuncionario")
    public Contato getContato() {
        return this.contato;
    }
    
    public void setContato(Contato contato) {
        this.contato = contato;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="enderecoFuncionario")
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pessoaFuncionario")
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    
    @Column(name="nomeFuncionario", length=50)
    public String getNomeFuncionario() {
        return this.nomeFuncionario;
    }
    
    public void setNomeFuncionario(String nomeFuncionario) {
        this.nomeFuncionario = nomeFuncionario;
    }

    
    @Column(name="cargoFuncionario", length=20)
    public String getCargoFuncionario() {
        return this.cargoFuncionario;
    }
    
    public void setCargoFuncionario(String cargoFuncionario) {
        this.cargoFuncionario = cargoFuncionario;
    }

    
    @Column(name="usuarioFuncionario", length=30)
    public String getUsuarioFuncionario() {
        return this.usuarioFuncionario;
    }
    
    public void setUsuarioFuncionario(String usuarioFuncionario) {
        this.usuarioFuncionario = usuarioFuncionario;
    }

    
    @Column(name="senhaFuncionario", length=30)
    public String getSenhaFuncionario() {
        return this.senhaFuncionario;
    }
    
    public void setSenhaFuncionario(String senhaFuncionario) {
        this.senhaFuncionario = senhaFuncionario;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="criacaoFuncionario", length=19)
    public Date getCriacaoFuncionario() {
        return this.criacaoFuncionario;
    }
    
    public void setCriacaoFuncionario(Date criacaoFuncionario) {
        this.criacaoFuncionario = criacaoFuncionario;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="atualizacaoFuncionario", length=19)
    public Date getAtualizacaoFuncionario() {
        return this.atualizacaoFuncionario;
    }
    
    public void setAtualizacaoFuncionario(Date atualizacaoFuncionario) {
        this.atualizacaoFuncionario = atualizacaoFuncionario;
    }




}


