package br.com.models.vo;
// Generated 16/06/2015 14:56:33 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Funcionario generated by hbm2java
 */
@Entity
@Table(name="funcionario"
    ,catalog="dbloja"
)
public class Funcionario  implements java.io.Serializable {


     private Long idFuncionario;
     private String nomeFuncionario;
     private String cargoFuncionario;
     private String usuarioFuncionario;
     private String senhaFuncionario;
     private String emailFuncionario;
     private String telefoneFuncionario;
     private String celularFuncionario;
     private String cpfFuncionario;
     private String rgFuncionario;
     private Date nascimentoFuncionario;
     private String enderecoFuncionario;
     private String cepFuncionario;
     private String complementoFuncionario;
     private String numeroFuncionario;
     private String cidadeFuncionario;
     private String bairroFuncionario;
     private String estadoFuncionario;
     private Date criacaoFuncionario;
     private Date atualizacaoFuncionario;

    public Funcionario() {
    }

    public Funcionario(String nomeFuncionario, String cargoFuncionario, String usuarioFuncionario, String senhaFuncionario, String emailFuncionario, String telefoneFuncionario, String celularFuncionario, String cpfFuncionario, String rgFuncionario, Date nascimentoFuncionario, String enderecoFuncionario, String cepFuncionario, String complementoFuncionario, String numeroFuncionario, String cidadeFuncionario, String bairroFuncionario, String estadoFuncionario, Date criacaoFuncionario, Date atualizacaoFuncionario) {
       this.nomeFuncionario = nomeFuncionario;
       this.cargoFuncionario = cargoFuncionario;
       this.usuarioFuncionario = usuarioFuncionario;
       this.senhaFuncionario = senhaFuncionario;
       this.emailFuncionario = emailFuncionario;
       this.telefoneFuncionario = telefoneFuncionario;
       this.celularFuncionario = celularFuncionario;
       this.cpfFuncionario = cpfFuncionario;
       this.rgFuncionario = rgFuncionario;
       this.nascimentoFuncionario = nascimentoFuncionario;
       this.enderecoFuncionario = enderecoFuncionario;
       this.cepFuncionario = cepFuncionario;
       this.complementoFuncionario = complementoFuncionario;
       this.numeroFuncionario = numeroFuncionario;
       this.cidadeFuncionario = cidadeFuncionario;
       this.bairroFuncionario = bairroFuncionario;
       this.estadoFuncionario = estadoFuncionario;
       this.criacaoFuncionario = criacaoFuncionario;
       this.atualizacaoFuncionario = atualizacaoFuncionario;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idFuncionario", unique=true, nullable=false)
    public Long getIdFuncionario() {
        return this.idFuncionario;
    }
    
    public void setIdFuncionario(Long idFuncionario) {
        this.idFuncionario = idFuncionario;
    }

    
    @Column(name="nomeFuncionario", length=50)
    public String getNomeFuncionario() {
        return this.nomeFuncionario;
    }
    
    public void setNomeFuncionario(String nomeFuncionario) {
        this.nomeFuncionario = nomeFuncionario;
    }

    
    @Column(name="cargoFuncionario", length=20)
    public String getCargoFuncionario() {
        return this.cargoFuncionario;
    }
    
    public void setCargoFuncionario(String cargoFuncionario) {
        this.cargoFuncionario = cargoFuncionario;
    }

    
    @Column(name="usuarioFuncionario", length=50)
    public String getUsuarioFuncionario() {
        return this.usuarioFuncionario;
    }
    
    public void setUsuarioFuncionario(String usuarioFuncionario) {
        this.usuarioFuncionario = usuarioFuncionario;
    }

    
    @Column(name="senhaFuncionario", length=50)
    public String getSenhaFuncionario() {
        return this.senhaFuncionario;
    }
    
    public void setSenhaFuncionario(String senhaFuncionario) {
        this.senhaFuncionario = senhaFuncionario;
    }

    
    @Column(name="emailFuncionario", length=50)
    public String getEmailFuncionario() {
        return this.emailFuncionario;
    }
    
    public void setEmailFuncionario(String emailFuncionario) {
        this.emailFuncionario = emailFuncionario;
    }

    
    @Column(name="telefoneFuncionario", length=20)
    public String getTelefoneFuncionario() {
        return this.telefoneFuncionario;
    }
    
    public void setTelefoneFuncionario(String telefoneFuncionario) {
        this.telefoneFuncionario = telefoneFuncionario;
    }

    
    @Column(name="celularFuncionario", length=20)
    public String getCelularFuncionario() {
        return this.celularFuncionario;
    }
    
    public void setCelularFuncionario(String celularFuncionario) {
        this.celularFuncionario = celularFuncionario;
    }

    
    @Column(name="cpfFuncionario", length=20)
    public String getCpfFuncionario() {
        return this.cpfFuncionario;
    }
    
    public void setCpfFuncionario(String cpfFuncionario) {
        this.cpfFuncionario = cpfFuncionario;
    }

    
    @Column(name="rgFuncionario", length=20)
    public String getRgFuncionario() {
        return this.rgFuncionario;
    }
    
    public void setRgFuncionario(String rgFuncionario) {
        this.rgFuncionario = rgFuncionario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="nascimentoFuncionario", length=10)
    public Date getNascimentoFuncionario() {
        return this.nascimentoFuncionario;
    }
    
    public void setNascimentoFuncionario(Date nascimentoFuncionario) {
        this.nascimentoFuncionario = nascimentoFuncionario;
    }

    
    @Column(name="enderecoFuncionario", length=100)
    public String getEnderecoFuncionario() {
        return this.enderecoFuncionario;
    }
    
    public void setEnderecoFuncionario(String enderecoFuncionario) {
        this.enderecoFuncionario = enderecoFuncionario;
    }

    
    @Column(name="cepFuncionario", length=20)
    public String getCepFuncionario() {
        return this.cepFuncionario;
    }
    
    public void setCepFuncionario(String cepFuncionario) {
        this.cepFuncionario = cepFuncionario;
    }

    
    @Column(name="complementoFuncionario", length=20)
    public String getComplementoFuncionario() {
        return this.complementoFuncionario;
    }
    
    public void setComplementoFuncionario(String complementoFuncionario) {
        this.complementoFuncionario = complementoFuncionario;
    }

    
    @Column(name="numeroFuncionario", length=10)
    public String getNumeroFuncionario() {
        return this.numeroFuncionario;
    }
    
    public void setNumeroFuncionario(String numeroFuncionario) {
        this.numeroFuncionario = numeroFuncionario;
    }

    
    @Column(name="cidadeFuncionario", length=20)
    public String getCidadeFuncionario() {
        return this.cidadeFuncionario;
    }
    
    public void setCidadeFuncionario(String cidadeFuncionario) {
        this.cidadeFuncionario = cidadeFuncionario;
    }

    
    @Column(name="bairroFuncionario", length=20)
    public String getBairroFuncionario() {
        return this.bairroFuncionario;
    }
    
    public void setBairroFuncionario(String bairroFuncionario) {
        this.bairroFuncionario = bairroFuncionario;
    }

    
    @Column(name="estadoFuncionario", length=20)
    public String getEstadoFuncionario() {
        return this.estadoFuncionario;
    }
    
    public void setEstadoFuncionario(String estadoFuncionario) {
        this.estadoFuncionario = estadoFuncionario;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="criacaoFuncionario", length=19)
    public Date getCriacaoFuncionario() {
        return this.criacaoFuncionario;
    }
    
    public void setCriacaoFuncionario(Date criacaoFuncionario) {
        this.criacaoFuncionario = criacaoFuncionario;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="atualizacaoFuncionario", length=19)
    public Date getAtualizacaoFuncionario() {
        return this.atualizacaoFuncionario;
    }
    
    public void setAtualizacaoFuncionario(Date atualizacaoFuncionario) {
        this.atualizacaoFuncionario = atualizacaoFuncionario;
    }




}


