package br.com.models.vo;
// Generated 24/06/2015 14:14:02 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name="item"
    ,catalog="dbloja"
)
public class Item  implements java.io.Serializable {


     private Long idItem;
     private Produto produto;
     private BigDecimal valorItem;
     private Date criacaoItem;
     private Date atualizacaoItem;
     private Set<Compra> compras = new HashSet<Compra>(0);
     private Set<Venda> vendas = new HashSet<Venda>(0);

    public Item() {
    }

    public Item(Produto produto, BigDecimal valorItem, Date criacaoItem, Date atualizacaoItem, Set<Compra> compras, Set<Venda> vendas) {
       this.produto = produto;
       this.valorItem = valorItem;
       this.criacaoItem = criacaoItem;
       this.atualizacaoItem = atualizacaoItem;
       this.compras = compras;
       this.vendas = vendas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idItem", unique=true, nullable=false)
    public Long getIdItem() {
        return this.idItem;
    }
    
    public void setIdItem(Long idItem) {
        this.idItem = idItem;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="produtoItem")
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }

    
    @Column(name="valorItem", precision=10)
    public BigDecimal getValorItem() {
        return this.valorItem;
    }
    
    public void setValorItem(BigDecimal valorItem) {
        this.valorItem = valorItem;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="criacaoItem", length=19)
    public Date getCriacaoItem() {
        return this.criacaoItem;
    }
    
    public void setCriacaoItem(Date criacaoItem) {
        this.criacaoItem = criacaoItem;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="atualizacaoItem", length=19)
    public Date getAtualizacaoItem() {
        return this.atualizacaoItem;
    }
    
    public void setAtualizacaoItem(Date atualizacaoItem) {
        this.atualizacaoItem = atualizacaoItem;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="item")
    public Set<Compra> getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set<Compra> compras) {
        this.compras = compras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="item")
    public Set<Venda> getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set<Venda> vendas) {
        this.vendas = vendas;
    }




}


