package br.com.models.vo;
// Generated 25/06/2015 16:48:08 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pessoafisica generated by hbm2java
 */
@Entity
@Table(name="pessoafisica"
    ,catalog="dbloja"
)
public class Pessoafisica  implements java.io.Serializable {


     private Long idPessoaFisica;
     private Pessoa pessoa;
     private String cpfPessoaFisica;
     private String rgPessoaFisica;
     private Date nascimentoPessoaFisica;
     private Date criacaoPessoaFisica;
     private Date atualizacaoPessoaFisica;

    public Pessoafisica() {
    }

    public Pessoafisica(Pessoa pessoa, String cpfPessoaFisica, String rgPessoaFisica, Date nascimentoPessoaFisica, Date criacaoPessoaFisica, Date atualizacaoPessoaFisica) {
       this.pessoa = pessoa;
       this.cpfPessoaFisica = cpfPessoaFisica;
       this.rgPessoaFisica = rgPessoaFisica;
       this.nascimentoPessoaFisica = nascimentoPessoaFisica;
       this.criacaoPessoaFisica = criacaoPessoaFisica;
       this.atualizacaoPessoaFisica = atualizacaoPessoaFisica;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idPessoaFisica", unique=true, nullable=false)
    public Long getIdPessoaFisica() {
        return this.idPessoaFisica;
    }
    
    public void setIdPessoaFisica(Long idPessoaFisica) {
        this.idPessoaFisica = idPessoaFisica;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pessoaPessoaFisica")
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    
    @Column(name="cpfPessoaFisica", length=20)
    public String getCpfPessoaFisica() {
        return this.cpfPessoaFisica;
    }
    
    public void setCpfPessoaFisica(String cpfPessoaFisica) {
        this.cpfPessoaFisica = cpfPessoaFisica;
    }

    
    @Column(name="rgPessoaFisica", length=20)
    public String getRgPessoaFisica() {
        return this.rgPessoaFisica;
    }
    
    public void setRgPessoaFisica(String rgPessoaFisica) {
        this.rgPessoaFisica = rgPessoaFisica;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="nascimentoPessoaFisica", length=10)
    public Date getNascimentoPessoaFisica() {
        return this.nascimentoPessoaFisica;
    }
    
    public void setNascimentoPessoaFisica(Date nascimentoPessoaFisica) {
        this.nascimentoPessoaFisica = nascimentoPessoaFisica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="criacaoPessoaFisica", length=19)
    public Date getCriacaoPessoaFisica() {
        return this.criacaoPessoaFisica;
    }
    
    public void setCriacaoPessoaFisica(Date criacaoPessoaFisica) {
        this.criacaoPessoaFisica = criacaoPessoaFisica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="atualizacaoPessoaFisica", length=19)
    public Date getAtualizacaoPessoaFisica() {
        return this.atualizacaoPessoaFisica;
    }
    
    public void setAtualizacaoPessoaFisica(Date atualizacaoPessoaFisica) {
        this.atualizacaoPessoaFisica = atualizacaoPessoaFisica;
    }




}


