package br.com.models.vo;
// Generated 19/06/2015 12:08:25 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pessoajuridica generated by hbm2java
 */
@Entity
@Table(name="pessoajuridica"
    ,catalog="dbloja"
)
public class Pessoajuridica  implements java.io.Serializable {


     private Long idPessoaJuridica;
     private Pessoa pessoa;
     private String cnpjPessoaJuridica;
     private String razaoSocialPessoaJuridica;
     private Date fundacaoPessoaJuridica;
     private String estadualPessoaJuridica;
     private String municipalPessoaJuridica;
     private String suframaPessoaJuridica;
     private Boolean icmsPessoaJuridica;

    public Pessoajuridica() {
    }

    public Pessoajuridica(Pessoa pessoa, String cnpjPessoaJuridica, String razaoSocialPessoaJuridica, Date fundacaoPessoaJuridica, String estadualPessoaJuridica, String municipalPessoaJuridica, String suframaPessoaJuridica, Boolean icmsPessoaJuridica) {
       this.pessoa = pessoa;
       this.cnpjPessoaJuridica = cnpjPessoaJuridica;
       this.razaoSocialPessoaJuridica = razaoSocialPessoaJuridica;
       this.fundacaoPessoaJuridica = fundacaoPessoaJuridica;
       this.estadualPessoaJuridica = estadualPessoaJuridica;
       this.municipalPessoaJuridica = municipalPessoaJuridica;
       this.suframaPessoaJuridica = suframaPessoaJuridica;
       this.icmsPessoaJuridica = icmsPessoaJuridica;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idPessoaJuridica", unique=true, nullable=false)
    public Long getIdPessoaJuridica() {
        return this.idPessoaJuridica;
    }
    
    public void setIdPessoaJuridica(Long idPessoaJuridica) {
        this.idPessoaJuridica = idPessoaJuridica;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pessoaPessoaJuridica")
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    
    @Column(name="cnpjPessoaJuridica", length=20)
    public String getCnpjPessoaJuridica() {
        return this.cnpjPessoaJuridica;
    }
    
    public void setCnpjPessoaJuridica(String cnpjPessoaJuridica) {
        this.cnpjPessoaJuridica = cnpjPessoaJuridica;
    }

    
    @Column(name="razaoSocialPessoaJuridica", length=20)
    public String getRazaoSocialPessoaJuridica() {
        return this.razaoSocialPessoaJuridica;
    }
    
    public void setRazaoSocialPessoaJuridica(String razaoSocialPessoaJuridica) {
        this.razaoSocialPessoaJuridica = razaoSocialPessoaJuridica;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fundacaoPessoaJuridica", length=10)
    public Date getFundacaoPessoaJuridica() {
        return this.fundacaoPessoaJuridica;
    }
    
    public void setFundacaoPessoaJuridica(Date fundacaoPessoaJuridica) {
        this.fundacaoPessoaJuridica = fundacaoPessoaJuridica;
    }

    
    @Column(name="estadualPessoaJuridica", length=45)
    public String getEstadualPessoaJuridica() {
        return this.estadualPessoaJuridica;
    }
    
    public void setEstadualPessoaJuridica(String estadualPessoaJuridica) {
        this.estadualPessoaJuridica = estadualPessoaJuridica;
    }

    
    @Column(name="municipalPessoaJuridica", length=45)
    public String getMunicipalPessoaJuridica() {
        return this.municipalPessoaJuridica;
    }
    
    public void setMunicipalPessoaJuridica(String municipalPessoaJuridica) {
        this.municipalPessoaJuridica = municipalPessoaJuridica;
    }

    
    @Column(name="suframaPessoaJuridica", length=45)
    public String getSuframaPessoaJuridica() {
        return this.suframaPessoaJuridica;
    }
    
    public void setSuframaPessoaJuridica(String suframaPessoaJuridica) {
        this.suframaPessoaJuridica = suframaPessoaJuridica;
    }

    
    @Column(name="icmsPessoaJuridica")
    public Boolean getIcmsPessoaJuridica() {
        return this.icmsPessoaJuridica;
    }
    
    public void setIcmsPessoaJuridica(Boolean icmsPessoaJuridica) {
        this.icmsPessoaJuridica = icmsPessoaJuridica;
    }




}


