package br.com.models.vo;
// Generated 09/05/2015 14:52:35 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Produto generated by hbm2java
 */
@Entity
@Table(name="produto"
    ,catalog="dbloja"
)
public class Produto  implements java.io.Serializable {


     private Long idProduto;
     private Categoria categoria;
     private Fornecedor fornecedor;
     private String nomeProduto;
     private BigDecimal valorProduto;
     private Integer quantidadeMinimaProduto;
     private Date dataCriacao;
     private Date dataAtualizacao;
     private Set<Item> items = new HashSet<Item>(0);

    public Produto() {
    }

	
    public Produto(Categoria categoria, String nomeProduto) {
        this.categoria = categoria;
        this.nomeProduto = nomeProduto;
    }
    public Produto(Categoria categoria, Fornecedor fornecedor, String nomeProduto, BigDecimal valorProduto, Integer quantidadeMinimaProduto, Date dataCriacao, Date dataAtualizacao, Set<Item> items) {
       this.categoria = categoria;
       this.fornecedor = fornecedor;
       this.nomeProduto = nomeProduto;
       this.valorProduto = valorProduto;
       this.quantidadeMinimaProduto = quantidadeMinimaProduto;
       this.dataCriacao = dataCriacao;
       this.dataAtualizacao = dataAtualizacao;
       this.items = items;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idProduto", unique=true, nullable=false)
    public Long getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(Long idProduto) {
        this.idProduto = idProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="categoriaProduto", nullable=false)
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fornecedorProduto")
    public Fornecedor getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }

    
    @Column(name="nomeProduto", nullable=false, length=30)
    public String getNomeProduto() {
        return this.nomeProduto;
    }
    
    public void setNomeProduto(String nomeProduto) {
        this.nomeProduto = nomeProduto;
    }

    
    @Column(name="valorProduto", precision=10)
    public BigDecimal getValorProduto() {
        return this.valorProduto;
    }
    
    public void setValorProduto(BigDecimal valorProduto) {
        this.valorProduto = valorProduto;
    }

    
    @Column(name="quantidadeMinimaProduto")
    public Integer getQuantidadeMinimaProduto() {
        return this.quantidadeMinimaProduto;
    }
    
    public void setQuantidadeMinimaProduto(Integer quantidadeMinimaProduto) {
        this.quantidadeMinimaProduto = quantidadeMinimaProduto;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dataCriacao", length=19)
    public Date getDataCriacao() {
        return this.dataCriacao;
    }
    
    public void setDataCriacao(Date dataCriacao) {
        this.dataCriacao = dataCriacao;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dataAtualizacao", length=19)
    public Date getDataAtualizacao() {
        return this.dataAtualizacao;
    }
    
    public void setDataAtualizacao(Date dataAtualizacao) {
        this.dataAtualizacao = dataAtualizacao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="produto")
    public Set<Item> getItems() {
        return this.items;
    }
    
    public void setItems(Set<Item> items) {
        this.items = items;
    }




}


