package br.com.model.vo;
// Generated 07/05/2015 20:54:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Fornecedor generated by hbm2java
 */
@Entity
@Table(name="fornecedor"
    ,catalog="dbloja"
)
public class Fornecedor  implements java.io.Serializable {


     private int idFornecedor;
     private String nomeFornecedor;
     private String empresa;
     private String telefone;
     private Set<Pedidofornecedor> pedidofornecedors = new HashSet<Pedidofornecedor>(0);

    public Fornecedor() {
    }

	
    public Fornecedor(int idFornecedor, String nomeFornecedor, String empresa, String telefone) {
        this.idFornecedor = idFornecedor;
        this.nomeFornecedor = nomeFornecedor;
        this.empresa = empresa;
        this.telefone = telefone;
    }
    public Fornecedor(int idFornecedor, String nomeFornecedor, String empresa, String telefone, Set<Pedidofornecedor> pedidofornecedors) {
       this.idFornecedor = idFornecedor;
       this.nomeFornecedor = nomeFornecedor;
       this.empresa = empresa;
       this.telefone = telefone;
       this.pedidofornecedors = pedidofornecedors;
    }
   
     @Id 

    
    @Column(name="id_fornecedor", unique=true, nullable=false)
    public int getIdFornecedor() {
        return this.idFornecedor;
    }
    
    public void setIdFornecedor(int idFornecedor) {
        this.idFornecedor = idFornecedor;
    }

    
    @Column(name="nomeFornecedor", nullable=false, length=30)
    public String getNomeFornecedor() {
        return this.nomeFornecedor;
    }
    
    public void setNomeFornecedor(String nomeFornecedor) {
        this.nomeFornecedor = nomeFornecedor;
    }

    
    @Column(name="empresa", nullable=false, length=30)
    public String getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="telefone", nullable=false, length=15)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fornecedor")
    public Set<Pedidofornecedor> getPedidofornecedors() {
        return this.pedidofornecedors;
    }
    
    public void setPedidofornecedors(Set<Pedidofornecedor> pedidofornecedors) {
        this.pedidofornecedors = pedidofornecedors;
    }




}


