package br.com.model.vo;
// Generated 07/05/2015 20:54:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Itempedido generated by hbm2java
 */
@Entity
@Table(name="itempedido"
    ,catalog="dbloja"
)
public class Itempedido  implements java.io.Serializable {


     private int idItem;
     private Produto produto;
     private int quantidade;
     private Set<Pedidofornecedor> pedidofornecedors = new HashSet<Pedidofornecedor>(0);
     private Set<Pedidocliente> pedidoclientes = new HashSet<Pedidocliente>(0);

    public Itempedido() {
    }

	
    public Itempedido(int idItem, Produto produto, int quantidade) {
        this.idItem = idItem;
        this.produto = produto;
        this.quantidade = quantidade;
    }
    public Itempedido(int idItem, Produto produto, int quantidade, Set<Pedidofornecedor> pedidofornecedors, Set<Pedidocliente> pedidoclientes) {
       this.idItem = idItem;
       this.produto = produto;
       this.quantidade = quantidade;
       this.pedidofornecedors = pedidofornecedors;
       this.pedidoclientes = pedidoclientes;
    }
   
     @Id 

    
    @Column(name="id_item", unique=true, nullable=false)
    public int getIdItem() {
        return this.idItem;
    }
    
    public void setIdItem(int idItem) {
        this.idItem = idItem;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_produto", nullable=false)
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }

    
    @Column(name="quantidade", nullable=false)
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="itempedido")
    public Set<Pedidofornecedor> getPedidofornecedors() {
        return this.pedidofornecedors;
    }
    
    public void setPedidofornecedors(Set<Pedidofornecedor> pedidofornecedors) {
        this.pedidofornecedors = pedidofornecedors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="itempedido")
    public Set<Pedidocliente> getPedidoclientes() {
        return this.pedidoclientes;
    }
    
    public void setPedidoclientes(Set<Pedidocliente> pedidoclientes) {
        this.pedidoclientes = pedidoclientes;
    }




}


