package br.com.model.vo;
// Generated 07/05/2015 21:01:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pedidofornecedor generated by hbm2java
 */
@Entity
@Table(name="pedidofornecedor"
    ,catalog="dbloja"
)
public class Pedidofornecedor  implements java.io.Serializable {


     private int idPedidoFornecedor;
     private Fornecedor fornecedor;
     private Itempedido itempedido;
     private Vendedor vendedor;
     private Set<Pedidoparceladofornecedor> pedidoparceladofornecedors = new HashSet<Pedidoparceladofornecedor>(0);

    public Pedidofornecedor() {
    }

	
    public Pedidofornecedor(int idPedidoFornecedor, Fornecedor fornecedor, Itempedido itempedido, Vendedor vendedor) {
        this.idPedidoFornecedor = idPedidoFornecedor;
        this.fornecedor = fornecedor;
        this.itempedido = itempedido;
        this.vendedor = vendedor;
    }
    public Pedidofornecedor(int idPedidoFornecedor, Fornecedor fornecedor, Itempedido itempedido, Vendedor vendedor, Set<Pedidoparceladofornecedor> pedidoparceladofornecedors) {
       this.idPedidoFornecedor = idPedidoFornecedor;
       this.fornecedor = fornecedor;
       this.itempedido = itempedido;
       this.vendedor = vendedor;
       this.pedidoparceladofornecedors = pedidoparceladofornecedors;
    }
   
     @Id 

    
    @Column(name="id_pedidoFornecedor", unique=true, nullable=false)
    public int getIdPedidoFornecedor() {
        return this.idPedidoFornecedor;
    }
    
    public void setIdPedidoFornecedor(int idPedidoFornecedor) {
        this.idPedidoFornecedor = idPedidoFornecedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_fornecedor", nullable=false)
    public Fornecedor getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_item", nullable=false)
    public Itempedido getItempedido() {
        return this.itempedido;
    }
    
    public void setItempedido(Itempedido itempedido) {
        this.itempedido = itempedido;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_vendedor", nullable=false)
    public Vendedor getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(Vendedor vendedor) {
        this.vendedor = vendedor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pedidofornecedor")
    public Set<Pedidoparceladofornecedor> getPedidoparceladofornecedors() {
        return this.pedidoparceladofornecedors;
    }
    
    public void setPedidoparceladofornecedors(Set<Pedidoparceladofornecedor> pedidoparceladofornecedors) {
        this.pedidoparceladofornecedors = pedidoparceladofornecedors;
    }




}


