package br.com.model.vo;
// Generated 09/05/2015 14:52:35 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedidoparceladofornecedor generated by hbm2java
 */
@Entity
@Table(name="pedidoparceladofornecedor"
    ,catalog="dbloja"
)
public class Pedidoparceladofornecedor  implements java.io.Serializable {


     private Integer idPedidoParceladoFornecedor;
     private Pedidofornecedor pedidofornecedor;
     private Date dataVencimento;
     private Integer status;
     private Date dataCriacao;
     private Date dataAtualizacao;

    public Pedidoparceladofornecedor() {
    }

	
    public Pedidoparceladofornecedor(Pedidofornecedor pedidofornecedor, Date dataVencimento) {
        this.pedidofornecedor = pedidofornecedor;
        this.dataVencimento = dataVencimento;
    }
    public Pedidoparceladofornecedor(Pedidofornecedor pedidofornecedor, Date dataVencimento, Integer status, Date dataCriacao, Date dataAtualizacao) {
       this.pedidofornecedor = pedidofornecedor;
       this.dataVencimento = dataVencimento;
       this.status = status;
       this.dataCriacao = dataCriacao;
       this.dataAtualizacao = dataAtualizacao;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idPedidoParceladoFornecedor", unique=true, nullable=false)
    public Integer getIdPedidoParceladoFornecedor() {
        return this.idPedidoParceladoFornecedor;
    }
    
    public void setIdPedidoParceladoFornecedor(Integer idPedidoParceladoFornecedor) {
        this.idPedidoParceladoFornecedor = idPedidoParceladoFornecedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pedidoFornecedor", nullable=false)
    public Pedidofornecedor getPedidofornecedor() {
        return this.pedidofornecedor;
    }
    
    public void setPedidofornecedor(Pedidofornecedor pedidofornecedor) {
        this.pedidofornecedor = pedidofornecedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataVencimento", nullable=false, length=10)
    public Date getDataVencimento() {
        return this.dataVencimento;
    }
    
    public void setDataVencimento(Date dataVencimento) {
        this.dataVencimento = dataVencimento;
    }

    
    @Column(name="status")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dataCriacao", length=19)
    public Date getDataCriacao() {
        return this.dataCriacao;
    }
    
    public void setDataCriacao(Date dataCriacao) {
        this.dataCriacao = dataCriacao;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dataAtualizacao", length=19)
    public Date getDataAtualizacao() {
        return this.dataAtualizacao;
    }
    
    public void setDataAtualizacao(Date dataAtualizacao) {
        this.dataAtualizacao = dataAtualizacao;
    }




}


