package br.com.model.vo;
// Generated 09/05/2015 14:52:35 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedidoparceladocliente generated by hbm2java
 */
@Entity
@Table(name="pedidoparceladocliente"
    ,catalog="dbloja"
)
public class Pedidoparceladocliente  implements java.io.Serializable {


     private Integer idPedidoParceladoCliente;
     private Pedidocliente pedidocliente;
     private Date dataVencimento;
     private Integer status;
     private Date dataCriacao;
     private Date dataAtualizacao;

    public Pedidoparceladocliente() {
    }

	
    public Pedidoparceladocliente(Pedidocliente pedidocliente, Date dataVencimento) {
        this.pedidocliente = pedidocliente;
        this.dataVencimento = dataVencimento;
    }
    public Pedidoparceladocliente(Pedidocliente pedidocliente, Date dataVencimento, Integer status, Date dataCriacao, Date dataAtualizacao) {
       this.pedidocliente = pedidocliente;
       this.dataVencimento = dataVencimento;
       this.status = status;
       this.dataCriacao = dataCriacao;
       this.dataAtualizacao = dataAtualizacao;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idPedidoParceladoCliente", unique=true, nullable=false)
    public Integer getIdPedidoParceladoCliente() {
        return this.idPedidoParceladoCliente;
    }
    
    public void setIdPedidoParceladoCliente(Integer idPedidoParceladoCliente) {
        this.idPedidoParceladoCliente = idPedidoParceladoCliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pedidoCliente", nullable=false)
    public Pedidocliente getPedidocliente() {
        return this.pedidocliente;
    }
    
    public void setPedidocliente(Pedidocliente pedidocliente) {
        this.pedidocliente = pedidocliente;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataVencimento", nullable=false, length=10)
    public Date getDataVencimento() {
        return this.dataVencimento;
    }
    
    public void setDataVencimento(Date dataVencimento) {
        this.dataVencimento = dataVencimento;
    }

    
    @Column(name="status")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dataCriacao", length=19)
    public Date getDataCriacao() {
        return this.dataCriacao;
    }
    
    public void setDataCriacao(Date dataCriacao) {
        this.dataCriacao = dataCriacao;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dataAtualizacao", length=19)
    public Date getDataAtualizacao() {
        return this.dataAtualizacao;
    }
    
    public void setDataAtualizacao(Date dataAtualizacao) {
        this.dataAtualizacao = dataAtualizacao;
    }




}


