package br.com.model.vo;
// Generated 07/05/2015 21:01:14 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedidoparceladocliente generated by hbm2java
 */
@Entity
@Table(name="pedidoparceladocliente"
    ,catalog="dbloja"
)
public class Pedidoparceladocliente  implements java.io.Serializable {


     private int idPedidoParceladoCliente;
     private Pedidocliente pedidocliente;
     private Date dtVenciemento;
     private Integer statusPedidoParcelado;

    public Pedidoparceladocliente() {
    }

	
    public Pedidoparceladocliente(int idPedidoParceladoCliente, Pedidocliente pedidocliente, Date dtVenciemento) {
        this.idPedidoParceladoCliente = idPedidoParceladoCliente;
        this.pedidocliente = pedidocliente;
        this.dtVenciemento = dtVenciemento;
    }
    public Pedidoparceladocliente(int idPedidoParceladoCliente, Pedidocliente pedidocliente, Date dtVenciemento, Integer statusPedidoParcelado) {
       this.idPedidoParceladoCliente = idPedidoParceladoCliente;
       this.pedidocliente = pedidocliente;
       this.dtVenciemento = dtVenciemento;
       this.statusPedidoParcelado = statusPedidoParcelado;
    }
   
     @Id 

    
    @Column(name="id_pedidoParceladoCliente", unique=true, nullable=false)
    public int getIdPedidoParceladoCliente() {
        return this.idPedidoParceladoCliente;
    }
    
    public void setIdPedidoParceladoCliente(int idPedidoParceladoCliente) {
        this.idPedidoParceladoCliente = idPedidoParceladoCliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pedidoCliente", nullable=false)
    public Pedidocliente getPedidocliente() {
        return this.pedidocliente;
    }
    
    public void setPedidocliente(Pedidocliente pedidocliente) {
        this.pedidocliente = pedidocliente;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dtVenciemento", nullable=false, length=10)
    public Date getDtVenciemento() {
        return this.dtVenciemento;
    }
    
    public void setDtVenciemento(Date dtVenciemento) {
        this.dtVenciemento = dtVenciemento;
    }

    
    @Column(name="statusPedidoParcelado")
    public Integer getStatusPedidoParcelado() {
        return this.statusPedidoParcelado;
    }
    
    public void setStatusPedidoParcelado(Integer statusPedidoParcelado) {
        this.statusPedidoParcelado = statusPedidoParcelado;
    }




}


