package br.com.model.vo;
// Generated 07/05/2015 21:01:14 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedidoparceladofornecedor generated by hbm2java
 */
@Entity
@Table(name="pedidoparceladofornecedor"
    ,catalog="dbloja"
)
public class Pedidoparceladofornecedor  implements java.io.Serializable {


     private int idPedidoParceladoFornecedor;
     private Pedidofornecedor pedidofornecedor;
     private Date dtVenciemento;
     private Integer statusPedidoParcelado;

    public Pedidoparceladofornecedor() {
    }

	
    public Pedidoparceladofornecedor(int idPedidoParceladoFornecedor, Pedidofornecedor pedidofornecedor, Date dtVenciemento) {
        this.idPedidoParceladoFornecedor = idPedidoParceladoFornecedor;
        this.pedidofornecedor = pedidofornecedor;
        this.dtVenciemento = dtVenciemento;
    }
    public Pedidoparceladofornecedor(int idPedidoParceladoFornecedor, Pedidofornecedor pedidofornecedor, Date dtVenciemento, Integer statusPedidoParcelado) {
       this.idPedidoParceladoFornecedor = idPedidoParceladoFornecedor;
       this.pedidofornecedor = pedidofornecedor;
       this.dtVenciemento = dtVenciemento;
       this.statusPedidoParcelado = statusPedidoParcelado;
    }
   
     @Id 

    
    @Column(name="id_pedidoParceladoFornecedor", unique=true, nullable=false)
    public int getIdPedidoParceladoFornecedor() {
        return this.idPedidoParceladoFornecedor;
    }
    
    public void setIdPedidoParceladoFornecedor(int idPedidoParceladoFornecedor) {
        this.idPedidoParceladoFornecedor = idPedidoParceladoFornecedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pedidoFornecedor", nullable=false)
    public Pedidofornecedor getPedidofornecedor() {
        return this.pedidofornecedor;
    }
    
    public void setPedidofornecedor(Pedidofornecedor pedidofornecedor) {
        this.pedidofornecedor = pedidofornecedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dtVenciemento", nullable=false, length=10)
    public Date getDtVenciemento() {
        return this.dtVenciemento;
    }
    
    public void setDtVenciemento(Date dtVenciemento) {
        this.dtVenciemento = dtVenciemento;
    }

    
    @Column(name="statusPedidoParcelado")
    public Integer getStatusPedidoParcelado() {
        return this.statusPedidoParcelado;
    }
    
    public void setStatusPedidoParcelado(Integer statusPedidoParcelado) {
        this.statusPedidoParcelado = statusPedidoParcelado;
    }




}


