package br.com.model.vo;
// Generated 07/05/2015 21:01:14 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Produto generated by hbm2java
 */
@Entity
@Table(name="produto"
    ,catalog="dbloja"
)
public class Produto  implements java.io.Serializable {


     private int idProduto;
     private Categoria categoria;
     private String nomeProduto;
     private int quantidadeMinima;
     private BigDecimal valorCusto;
     private Set<Itempedido> itempedidos = new HashSet<Itempedido>(0);

    public Produto() {
    }

	
    public Produto(int idProduto, Categoria categoria, String nomeProduto, int quantidadeMinima, BigDecimal valorCusto) {
        this.idProduto = idProduto;
        this.categoria = categoria;
        this.nomeProduto = nomeProduto;
        this.quantidadeMinima = quantidadeMinima;
        this.valorCusto = valorCusto;
    }
    public Produto(int idProduto, Categoria categoria, String nomeProduto, int quantidadeMinima, BigDecimal valorCusto, Set<Itempedido> itempedidos) {
       this.idProduto = idProduto;
       this.categoria = categoria;
       this.nomeProduto = nomeProduto;
       this.quantidadeMinima = quantidadeMinima;
       this.valorCusto = valorCusto;
       this.itempedidos = itempedidos;
    }
   
     @Id 

    
    @Column(name="id_produto", unique=true, nullable=false)
    public int getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(int idProduto) {
        this.idProduto = idProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_categoria", nullable=false)
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }

    
    @Column(name="nomeProduto", nullable=false, length=30)
    public String getNomeProduto() {
        return this.nomeProduto;
    }
    
    public void setNomeProduto(String nomeProduto) {
        this.nomeProduto = nomeProduto;
    }

    
    @Column(name="quantidadeMinima", nullable=false)
    public int getQuantidadeMinima() {
        return this.quantidadeMinima;
    }
    
    public void setQuantidadeMinima(int quantidadeMinima) {
        this.quantidadeMinima = quantidadeMinima;
    }

    
    @Column(name="valorCusto", nullable=false, precision=10)
    public BigDecimal getValorCusto() {
        return this.valorCusto;
    }
    
    public void setValorCusto(BigDecimal valorCusto) {
        this.valorCusto = valorCusto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="produto")
    public Set<Itempedido> getItempedidos() {
        return this.itempedidos;
    }
    
    public void setItempedidos(Set<Itempedido> itempedidos) {
        this.itempedidos = itempedidos;
    }




}


