package br.com.model.vo;
// Generated 07/05/2015 20:54:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vendedor generated by hbm2java
 */
@Entity
@Table(name="vendedor"
    ,catalog="dbloja"
)
public class Vendedor  implements java.io.Serializable {


     private int idVendedor;
     private String nomeVendedor;
     private String cpf;
     private String endereco;
     private String telefone;
     private String email;
     private Set<Pedidocliente> pedidoclientes = new HashSet<Pedidocliente>(0);
     private Set<Pedidofornecedor> pedidofornecedors = new HashSet<Pedidofornecedor>(0);

    public Vendedor() {
    }

	
    public Vendedor(int idVendedor, String nomeVendedor, String cpf) {
        this.idVendedor = idVendedor;
        this.nomeVendedor = nomeVendedor;
        this.cpf = cpf;
    }
    public Vendedor(int idVendedor, String nomeVendedor, String cpf, String endereco, String telefone, String email, Set<Pedidocliente> pedidoclientes, Set<Pedidofornecedor> pedidofornecedors) {
       this.idVendedor = idVendedor;
       this.nomeVendedor = nomeVendedor;
       this.cpf = cpf;
       this.endereco = endereco;
       this.telefone = telefone;
       this.email = email;
       this.pedidoclientes = pedidoclientes;
       this.pedidofornecedors = pedidofornecedors;
    }
   
     @Id 

    
    @Column(name="id_vendedor", unique=true, nullable=false)
    public int getIdVendedor() {
        return this.idVendedor;
    }
    
    public void setIdVendedor(int idVendedor) {
        this.idVendedor = idVendedor;
    }

    
    @Column(name="nomeVendedor", nullable=false, length=30)
    public String getNomeVendedor() {
        return this.nomeVendedor;
    }
    
    public void setNomeVendedor(String nomeVendedor) {
        this.nomeVendedor = nomeVendedor;
    }

    
    @Column(name="cpf", nullable=false, length=15)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    
    @Column(name="endereco", length=50)
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    
    @Column(name="telefone", length=15)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    
    @Column(name="email", length=20)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vendedor")
    public Set<Pedidocliente> getPedidoclientes() {
        return this.pedidoclientes;
    }
    
    public void setPedidoclientes(Set<Pedidocliente> pedidoclientes) {
        this.pedidoclientes = pedidoclientes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vendedor")
    public Set<Pedidofornecedor> getPedidofornecedors() {
        return this.pedidofornecedors;
    }
    
    public void setPedidofornecedors(Set<Pedidofornecedor> pedidofornecedors) {
        this.pedidofornecedors = pedidofornecedors;
    }




}


