package br.com.models.entity;
// Generated 30/04/2015 19:57:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente"
    ,catalog="fenixdb"
)
public class Cliente  implements java.io.Serializable {


     private long idCliente;
     private Set<Pedidocliente> pedidoclientes = new HashSet<Pedidocliente>(0);

    public Cliente() {
    }

	
    public Cliente(long idCliente) {
        this.idCliente = idCliente;
    }
    public Cliente(long idCliente, Set<Pedidocliente> pedidoclientes) {
       this.idCliente = idCliente;
       this.pedidoclientes = pedidoclientes;
    }
   
     @Id 

    
    @Column(name="idCliente", unique=true, nullable=false)
    public long getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(long idCliente) {
        this.idCliente = idCliente;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set<Pedidocliente> getPedidoclientes() {
        return this.pedidoclientes;
    }
    
    public void setPedidoclientes(Set<Pedidocliente> pedidoclientes) {
        this.pedidoclientes = pedidoclientes;
    }




}


