package br.com.models.entity;
// Generated 30/04/2015 19:57:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Fornecedor generated by hbm2java
 */
@Entity
@Table(name="fornecedor"
    ,catalog="fenixdb"
)
public class Fornecedor  implements java.io.Serializable {


     private long idFornecedor;
     private Set<Pedidofornecedor> pedidofornecedors = new HashSet<Pedidofornecedor>(0);

    public Fornecedor() {
    }

	
    public Fornecedor(long idFornecedor) {
        this.idFornecedor = idFornecedor;
    }
    public Fornecedor(long idFornecedor, Set<Pedidofornecedor> pedidofornecedors) {
       this.idFornecedor = idFornecedor;
       this.pedidofornecedors = pedidofornecedors;
    }
   
     @Id 

    
    @Column(name="idFornecedor", unique=true, nullable=false)
    public long getIdFornecedor() {
        return this.idFornecedor;
    }
    
    public void setIdFornecedor(long idFornecedor) {
        this.idFornecedor = idFornecedor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fornecedor")
    public Set<Pedidofornecedor> getPedidofornecedors() {
        return this.pedidofornecedors;
    }
    
    public void setPedidofornecedors(Set<Pedidofornecedor> pedidofornecedors) {
        this.pedidofornecedors = pedidofornecedors;
    }




}


