package br.com.models.entity;
// Generated 30/04/2015 19:57:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name="item"
    ,catalog="fenixdb"
)
public class Item  implements java.io.Serializable {


     private long idItem;
     private Produto produto;
     private Set<Pedidofornecedor> pedidofornecedors = new HashSet<Pedidofornecedor>(0);
     private Set<Pedidocliente> pedidoclientes = new HashSet<Pedidocliente>(0);

    public Item() {
    }

	
    public Item(long idItem, Produto produto) {
        this.idItem = idItem;
        this.produto = produto;
    }
    public Item(long idItem, Produto produto, Set<Pedidofornecedor> pedidofornecedors, Set<Pedidocliente> pedidoclientes) {
       this.idItem = idItem;
       this.produto = produto;
       this.pedidofornecedors = pedidofornecedors;
       this.pedidoclientes = pedidoclientes;
    }
   
     @Id 

    
    @Column(name="idItem", unique=true, nullable=false)
    public long getIdItem() {
        return this.idItem;
    }
    
    public void setIdItem(long idItem) {
        this.idItem = idItem;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="itemProduto", nullable=false)
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="item")
    public Set<Pedidofornecedor> getPedidofornecedors() {
        return this.pedidofornecedors;
    }
    
    public void setPedidofornecedors(Set<Pedidofornecedor> pedidofornecedors) {
        this.pedidofornecedors = pedidofornecedors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="item")
    public Set<Pedidocliente> getPedidoclientes() {
        return this.pedidoclientes;
    }
    
    public void setPedidoclientes(Set<Pedidocliente> pedidoclientes) {
        this.pedidoclientes = pedidoclientes;
    }




}


