package br.com.models.entity;
// Generated 30/04/2015 19:57:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Produto generated by hbm2java
 */
@Entity
@Table(name="produto"
    ,catalog="fenixdb"
)
public class Produto  implements java.io.Serializable {


     private long idProduto;
     private Set<Item> items = new HashSet<Item>(0);

    public Produto() {
    }

	
    public Produto(long idProduto) {
        this.idProduto = idProduto;
    }
    public Produto(long idProduto, Set<Item> items) {
       this.idProduto = idProduto;
       this.items = items;
    }
   
     @Id 

    
    @Column(name="idProduto", unique=true, nullable=false)
    public long getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(long idProduto) {
        this.idProduto = idProduto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="produto")
    public Set<Item> getItems() {
        return this.items;
    }
    
    public void setItems(Set<Item> items) {
        this.items = items;
    }




}


